### ISSUE TITLE
Tool failed during DEQ testing

### ISSUE THREAD

**Issue by nathankota** [agrc/DEQ-TankRisk#17]
> It ran for awhile and then failed.  Below is the details.

```
Start Time: Thursday, December 12, 2019 7:12:16 AM
Running script TankRisk...
Version 2.0.0
Calculating risks from StreamsNHDHighRes
StreamsNHDHighRes risks calculated in 2.19 minutes
Calculating risks from LakesNHDHighRes
LakesNHDHighRes risks calculated in 20614 ms's
Calculating risks from CensusTracts2010
CensusTracts2010 risks calculated in 30.43 seconds
Calculating risks from ShallowGroundWater
ShallowGroundWater risks calculated in 8700 ms's
Calculating risks from Soils
Soils risks calculated in 2.6 minutes
Calculating risks from DWQAssessmentUnits
DWQAssessmentUnits risks calculated in 79.84 seconds
Calculating risks from Aquifer_RechargeDischargeAreas
Aquifer_RechargeDischargeAreas risks calculated in 15522 ms's
Calculating risks from wrpod
wrpod risks calculated in 16096 ms's
Calculating risks from Wetlands
Wetlands risks calculated in 66.96 seconds
Calculating risks from SurfaceWaterZones
 Traceback (most recent call last):
  File "<string>", line 521, in execute
  File "<string>", line 613, in start
  File "<string>", line 450, in update_tank_results
  File "<string>", line 326, in update_tank_value_and_score
AttributeError: 'TankResult' object has no attribute 'getSevForLayer'
 Failed to execute (TankRisk).
Failed at Thursday, December 12, 2019 7:21:30 AM (Elapsed Time: 9 minutes 13 seconds)
```

**Comment by nathankota** [comment]
After DEQ testing of [beta.1](https://github.com/agrc/DEQ-TankRisk/releases/tag/2.0.0-beta.1):

>  It ran, but the last two output columns were blank.
